### ISSUE TITLE
[BUG] Content not showing as available when searched.

### ISSUE THREAD

**Issue by LFFPicard** [linuxserver/docker-overseerr#23]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When searching the content does not show as available, end user then requests the item. I can see the request but it shows as available so decline the request.

### Expected Behavior

Content shows as available when searched.

### Steps To Reproduce

Search for content

### Environment

```markdown
- OS: Unraid 6.11.5
- How docker service was installed: linuxserver container.
```

### CPU architecture

x86-64

### Docker creation

```bash
https://imgur.com/a/YPrfX0M
```

### Container logs

```bash
https://pastebin.com/jrD6c4Le
```

**Comment by LFFPicard** [comment]
I have tried doing a re-sync a number of times but this has not helped. To clarify this does not happen to everything, alot of content does show as available so it seems a bit random.

https://imgur.com/OoKa1jd
https://imgur.com/8ItsVb4

**Comment by Roxedus** [comment]
This is a application issue, not a container issue.
