### ISSUE TITLE
[BUG] BTRFS errors in v1.33.2-ls113

### ISSUE THREAD

**Issue by Sempiternity87** [linuxserver/docker-overseerr#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I had been running on the latest version in Unraid, when I noticed my syslog was filling up with BTRFS errors. I had also noticed a bit earlier that Overseerr wasn't working (app was running, but couldn't reach it). I was going through some trouble-shooting and didn't notice the relationship until I had disabled Docker, and the BTRFS errors stopped. Then I turned it back on (got the errors again), and remembered Overseerr not working, so stopped that app specifically, and my errors went away.

I came here to see if there were any issues reported, but finding nothing, I looked at some recent changes (nothing stood out to me). I figured if there was an issue with a recent version, I could try an older one. Updating my container to v1.33.2-ls112 has Overseerr working again, and no BTRFS errors.

To double check again, I set the container to v1.33.2-ls113 specifically, and my issues cropped up again. Back to v1.33.2-ls112 and it was fine. I'm not sure what changed, but it's definitely having an issue with something.

### Expected Behavior

Container should be running and accessible, with no errors.

### Steps To Reproduce

Running the Docker container using the latest repository, or specifically "lscr.io/linuxserver/overseerr:v1.33.2-ls113"

### Environment

```markdown
- OS: Unraid 6.12.10
- How docker service was installed: Installed from Community Applications
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run
  -d
  --name='overseerr'
  --net='bridge'
  -e TZ="America/Los_Angeles"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Deponia"
  -e HOST_CONTAINERNAME="overseerr"
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:5055]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/overseerr-logo.png'
  -p '5055:5055/tcp'
  -v '/mnt/user/appdata/overseerr':'/config':'rw' 'lscr.io/linuxserver/overseerr:v1.33.2-ls113'
bea051406684674ed13af4abd7798495062177de0a06898a338e066940231147
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
Overseerr Github Sponsors: https://github.com/sponsors/sct
Overseerr Patreon: https://patreon.com/overseerr

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────
Linuxserver.io version: v1.33.2-ls113
Build-date: 2024-07-17T18:43:31+00:00
───────────────────────────────────────
    
[custom-init] No custom files found, skipping...
```

**Comment by j0nnymoe** [comment]
A copy of the btrfs errors would be helpful but I suspect this might be a corrupted docker.img maybe.

**Comment by Sempiternity87** [comment]
Yeah, that's what I've been trying to find out for the last week. One of the things that's been confusing me is that I recently (in the last month or so) converted my cache drive from BTRFS to XFS. The error is the same, constantly (and filling up my log). The only thing that's different is the "corrupt" count.

I wasn't sure if it was a corrupted docker.img since the errors stopped when I stopped the Overseerr container.
```
Jul 26 12:09:45 Deponia kernel: BTRFS warning (device loop2): csum failed root 1156 ino 61914 off 921600 csum 0xd57aab0a expected csum 0x3ab67240 mirror 1
Jul 26 12:09:45 Deponia kernel: BTRFS error (device loop2): bdev /dev/loop2 errs: wr 0, rd 0, flush 0, corrupt 1192925, gen 0
Jul 26 12:09:46 Deponia kernel: BTRFS warning (device loop2): csum failed root 1156 ino 61914 off 921600 csum 0xd57aab0a expected csum 0x3ab67240 mirror 1
Jul 26 12:09:46 Deponia kernel: BTRFS error (device loop2): bdev /dev/loop2 errs: wr 0, rd 0, flush 0, corrupt 1192926, gen 0
Jul 26 12:09:46 Deponia kernel: BTRFS warning (device loop2): csum failed root 1156 ino 61914 off 921600 csum 0xd57aab0a expected csum 0x3ab67240 mirror 1
Jul 26 12:09:46 Deponia kernel: BTRFS error (device loop2): bdev /dev/loop2 errs: wr 0, rd 0, flush 0, corrupt 1192927, gen 0
Jul 26 12:09:47 Deponia kernel: BTRFS warning (device loop2): csum failed root 1156 ino 61914 off 921600 csum 0xd57aab0a expected csum 0x3ab67240 mirror 1
Jul 26 12:09:47 Deponia kernel: BTRFS error (device loop2): bdev /dev/loop2 errs: wr 0, rd 0, flush 0, corrupt 1192928, gen 0
Jul 26 12:09:47 Deponia kernel: BTRFS warning (device loop2): csum failed root 1156 ino 61914 off 921600 csum 0xd57aab0a expected csum 0x3ab67240 mirror 1
Jul 26 12:09:47 Deponia kernel: BTRFS error (device loop2): bdev /dev/loop2 errs: wr 0, rd 0, flush 0, corrupt 1192929, gen 0
Jul 26 12:09:48 Deponia kernel: BTRFS warning (device loop2): csum failed root 1156 ino 61914 off 921600 csum 0xd57aab0a expected csum 0x3ab67240 mirror 1
Jul 26 12:09:48 Deponia kernel: BTRFS error (device loop2): bdev /dev/loop2 errs: wr 0, rd 0, flush 0, corrupt 1192930, gen 0
Jul 26 12:09:48 Deponia kernel: BTRFS warning (device loop2): csum failed root 1156 ino 61914 off 921600 csum 0xd57aab0a expected csum 0x3ab67240 mirror 1
Jul 26 12:09:48 Deponia kernel: BTRFS error (device loop2): bdev /dev/loop2 errs: wr 0, rd 0, flush 0, corrupt 1192931, gen 0
```

**Comment by j0nnymoe** [comment]
Yea those are host level issues, not anything to do with the container.

**Comment by drizuid** [comment]
what is the docker storage driver set to? overlayfs is default and does not support btrfs. regardless, this is not a container issue, it's a host issue. closing due to no response from OP and being out of scope.
